// lib/models.dart
// Modèles pour BasedFit - Projet BasedFit

/// Modèle d'exercice
class Exercise {
  final String id;
  final String name;
  final String image;
  final String muscleGroup;
  final String equipment;
  final bool isFavorite;

  Exercise({
    required this.id,
    required this.name,
    required this.image,
    required this.muscleGroup,
    required this.equipment,
    this.isFavorite = false,
  });

  /// Conversion pour SQLite
  Map<String, dynamic> toMap() => {
        'id': id,
        'name': name,
        'image': image,
        'muscle_group': muscleGroup,
        'equipment': equipment,
        'is_favorite': isFavorite ? 1 : 0,
      };

  /// Création depuis SQLite
  factory Exercise.fromMap(Map<String, dynamic> map) => Exercise(
        id: map['id'].toString(),
        name: map['name'] as String,
        image: map['image'] as String,
        muscleGroup: map['muscle_group'] as String,
        equipment: map['equipment'] as String,
        isFavorite: (map['is_favorite'] as int) == 1,
      );

  /// Copie avec modification
  Exercise copyWith({
    String? id,
    String? name,
    String? image,
    String? muscleGroup,
    String? equipment,
    bool? isFavorite,
  }) {
    return Exercise(
      id: id ?? this.id,
      name: name ?? this.name,
      image: image ?? this.image,
      muscleGroup: muscleGroup ?? this.muscleGroup,
      equipment: equipment ?? this.equipment,
      isFavorite: isFavorite ?? this.isFavorite,
    );
  }
}

/// Exercice sélectionné avec ses paramètres
class SelectedExercise {
  Exercise exercise;
  int sets;
  int reps;
  double weight;
  int rest;
  String notes;

  SelectedExercise(
    this.exercise, {
    this.sets = 3,
    this.reps = 10,
    this.weight = 0,
    this.rest = 60,
    this.notes = '',
  });

  /// Conversion pour SQLite
  Map<String, dynamic> toMap({required int programId}) => {
        'program_id': programId,
        'exercise_id': exercise.id,
        'name': exercise.name,
        'image': exercise.image,
        'muscle_group': exercise.muscleGroup,
        'equipment': exercise.equipment,
        'is_favorite': exercise.isFavorite ? 1 : 0,
        'sets': sets,
        'reps': reps,
        'weight': weight,
        'rest': rest,
        'notes': notes,
      };

  /// Création depuis SQLite
  factory SelectedExercise.fromMap(Map<String, dynamic> map) {
    final exercise = Exercise.fromMap(map);
    return SelectedExercise(
      exercise,
      sets: map['sets'] as int,
      reps: map['reps'] as int,
      weight: (map['weight'] as num).toDouble(),
      rest: map['rest'] as int,
      notes: map['notes'] as String? ?? '',
    );
  }

  /// Copie avec modification
  SelectedExercise copyWith({
    Exercise? exercise,
    int? sets,
    int? reps,
    double? weight,
    int? rest,
    String? notes,
  }) {
    return SelectedExercise(
      exercise ?? this.exercise,
      sets: sets ?? this.sets,
      reps: reps ?? this.reps,
      weight: weight ?? this.weight,
      rest: rest ?? this.rest,
      notes: notes ?? this.notes,
    );
  }
}

/// Programme d'entraînement complet
class WorkoutProgram {
  final int? id;
  final String name;
  final double duration; // en minutes
  final List<SelectedExercise> exercises;
  final DateTime createdAt;
  final DateTime? updatedAt;

  WorkoutProgram({
    this.id,
    required this.name,
    required this.duration,
    required this.exercises,
    DateTime? createdAt,
    this.updatedAt,
  }) : createdAt = createdAt ?? DateTime.now();

  /// Conversion pour SQLite
  Map<String, dynamic> toMap() => {
        'name': name,
        'duration': duration,
        'created_at': createdAt.toIso8601String(),
        'updated_at': updatedAt?.toIso8601String(),
      };

  /// Création depuis SQLite
  factory WorkoutProgram.fromMap(Map<String, dynamic> map) {
    // Cette méthode est gérée dans le repository
    throw UnimplementedError('Use repository.getProgram()');
  }

  /// Copie avec modification
  WorkoutProgram copyWith({
    int? id,
    String? name,
    double? duration,
    List<SelectedExercise>? exercises,
    DateTime? createdAt,
    DateTime? updatedAt,
  }) {
    return WorkoutProgram(
      id: id ?? this.id,
      name: name ?? this.name,
      duration: duration ?? this.duration,
      exercises: exercises ?? this.exercises,
      createdAt: createdAt ?? this.createdAt,
      updatedAt: updatedAt ?? this.updatedAt,
    );
  }

  /// Calcule la durée du programme
  double calculateDuration() {
    return exercises.fold(
      0.0,
      (total, se) => total + (se.sets * (se.reps * 0.3 + se.rest / 60)),
    );
  }
}

/// Modèle pour les programmes générés automatiquement (futur)
class AutoGeneratedProgram {
  final String goal;
  final int durationWeeks;
  final List<WorkoutProgram> programs;

  AutoGeneratedProgram({
    required this.goal,
    required this.durationWeeks,
    required this.programs,
  });
}
